### ISSUE TITLE
`Exception: b'/bin/sh: 1: firefox: not found\n'` encountered while attempting to install/configure ansible role

### ISSUE THREAD

**Issue by capsulecorplab** [staticdev/ansible-role-firefox#129]
I'm encountering the following exception while attempting to install/configure the ansible role
```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1674603780.0506513-450-204423107100632/AnsiballZ_firefox_profile.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1674603780.0506513-450-204423107100632/AnsiballZ_firefox_profile.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1674603780.0506513-450-204423107100632/AnsiballZ_firefox_profile.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible.modules.firefox_profile', init_globals=dict(_module_fqn='ansible.modules.firefox_profile', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_firefox_profile_payload_b4mdivjc/ansible_firefox_profile_payload.zip/ansible/modules/firefox_profile.py", line 119, in <module>
  File "/tmp/ansible_firefox_profile_payload_b4mdivjc/ansible_firefox_profile_payload.zip/ansible/modules/firefox_profile.py", line 109, in main
  File "/tmp/ansible_firefox_profile_payload_b4mdivjc/ansible_firefox_profile_payload.zip/ansible/modules/firefox_profile.py", line 88, in create
Exception: b'/bin/sh: 1: firefox: not found\n'
```

See https://github.com/tetrabiodistributed/tetra-workspace-image/actions/runs/4001442035/jobs/6867670993#step:5:948 for exception
Playbook details here https://github.com/tetrabiodistributed/tetra-workspace-image/blob/70c6825db805643f12551c3f980df2973d6bd1e6/playbook.yaml#L391

**Comment by staticdev** [comment]
@capsulecorplab I will try to push a bugfix ASAP.

**Comment by staticdev** [comment]
@capsulecorplab fixed on version 1.2.3.

**Comment by capsulecorplab** [comment]
@staticdev still encountering a build error on my CI https://github.com/tetrabiodistributed/tetra-workspace-image/actions/runs/4001442035/jobs/6944033750#step:5:981 Should I open a separate issue for this or is this part of the same issue?

**Comment by staticdev** [comment]
@capsulecorplab what distro of Linux are you using?

**Comment by capsulecorplab** [comment]
@staticdev Ubuntu 20.04 (Focal)

**Comment by staticdev** [comment]
@capsulecorplab this is very strange, since on CI/CD this role is tested exactly with Ubuntu Focal.

**Comment by staticdev** [comment]
I need to understand what happens on your APT.. maybe something is misconfigured.

**Comment by capsulecorplab** [comment]
@staticdev build passed just fine installing with apt https://github.com/tetrabiodistributed/tetra-workspace-image/actions/runs/4047779659/jobs/6962215629
Just pulled and ran the image and was able to open firefox
![Screenshot from 2023-01-30 13-35-46](https://user-images.githubusercontent.com/14095576/215589477-ffb86e69-f491-46e7-a813-b52777754d36.png)

**Comment by staticdev** [comment]
@capsulecorplab this is what the ansible role is doing under the hood. Maybe the it needs to update the repository. We can do another test.. Instead of instelling with apt, do a `apt update` before running the role. If it works I will have to add this step also to the role.

**Comment by capsulecorplab** [comment]
@staticdev still same issue :confused: https://github.com/tetrabiodistributed/tetra-workspace-image/actions/runs/4059523912/jobs/6987656046#step:5:1002

**Comment by staticdev** [comment]
@capsulecorplab sorry for late response. I checked the last logs you sent me and found no `apt update' running before the file.

**Comment by capsulecorplab** [comment]
This is the commit that generated the aforementioned build https://github.com/tetrabiodistributed/tetra-workspace-image/commit/2d2faca14c5f525f59d0aadce9c7a4bcbbf0fbfa
Am I missing something in the ansible playbook?

**Comment by capsulecorplab** [comment]
@staticdev sorry for the late reply, I just tested the image built with the pretask and it seems to be working! Got a warning that I'm running an older version of firefox though,

![Screenshot from 2023-03-20 10-32-56](https://user-images.githubusercontent.com/14095576/226421695-a2fe8824-da2a-4323-97ac-d0df9cd74674.png)

![Screenshot from 2023-03-20 10-33-06](https://user-images.githubusercontent.com/14095576/226421730-b0b53174-b8a4-4d7c-83bc-f20697b9e794.png)

**Comment by staticdev** [comment]
@capsulecorplab this warning is known but is a limitation of Debian being a bit slow to update Firefox ESR on their APT repos. Will close it then. Thanks
